trigger:
  branches:
    include:
      - main
# wwe only publish docs when we push to main. We shuold have a docs staging site tho.
# pr:
#   branches:
#     include:
#       - '*'
#     # must quote since "*" is a YAML reserved character; we want a string

stages:
  - stage: Build_the_Docs
    jobs:
      - job: Linux
        pool:
          name: Hosted Ubuntu 1604
          demands: npm
        strategy:
          matrix:
            node_12_x:
              node_version: 12.x

        steps:
          - template: .azure-pipelines/build.docs.yml
          - template: .azure-pipelines/create-release.docs.yml

  - stage: Release_the_docs
    jobs:
      - job: Push_to_Storage
        pool:
          name: Hosted Ubuntu 1604
        strategy:
          matrix:
            node_12_x:
              node_version: 12.x

        steps:
          - template: .azure-pipelines/publish-release.docs.yml
